stages:
  - build
  - package
  - codeQuality
  
build_gcc:
  tags:
    - gcc_linux
  stage: build
  allow_failure: false
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install gcc g++ make libncurses5-dev libncursesw5-dev cmake -y
  script:
    - cmake .
    - make

build_clang:
  only:
    - master
  stage: build
  image: ubuntu:bionic
  allow_failure: false
  before_script:
    - apt-get update
    - apt-get install clang libncurses5-dev libncursesw5-dev cmake -y
  script:
    - cmake .
    - make

canvas_submit:
  only:
    - master
  stage: package
  image: ubuntu:bionic
  allow_failure: true
  script:
    - whoami
