stages:
  - build

build_gcc:
  statges: build
  image: gcc:latest
  allow_failure: false
  before_script:
    - apt-get update -y
    - apt-get install cmake libncurses5-dev libncursesw5-dev -y
  script:
    - cmake.
    - make
