stages:
  - build
  - changelog
  - packaging
  
build_gcc:
  tags:
    - gcc_linux
  stage: build
  allow_failure: false
  script:
    - cmake .
    - make

build_clang:
  only:
    - master
  stage: build
  image: ubuntu:bionic
  allow_failure: false
  before_script:
    - apt-get update
    - apt-get install clang libncurses5-dev libncursesw5-dev cmake -y
  script:
    - cmake .
    - make

update_changelog:
  tags:
    - changelog
  only:
    - master
  stage: changelog
  image: ferrarimarco/github-changelog-generator
  script:
    - github_changelog_generator --user "${GITLAB_USER}" --project "${GITLAB_PROJECT}" --github-site "${GITLAB_SITE}" --github-api "${GITLAB_API}" --verbose --gitlab
